<?xml version="1.0" encoding="utf-8"?><Database Name="GreenhouseDB" Class="ProvaGreenHouseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=GreenhouseDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="GreenHouse_App.Properties.Settings" SettingsPropertyName="GreenhouseDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCESSI_INVENTARIO" Member="ACCESSI_INVENTARIO">
    <Type Name="ACCESSI_INVENTARIO">
      <Column Name="IDDipendente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataOra" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDGarage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDSerraIncubazione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DIPENDENTI_ACCESSI_INVENTARIO" Member="DIPENDENTI" ThisKey="IDDipendente" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
      <Association Name="GARAGE_ACCESSI_INVENTARIO" Member="GARAGE" ThisKey="IDStruttura,IDGarage" OtherKey="IDStruttura,IDGarage" Type="GARAGE" IsForeignKey="true" />
      <Association Name="MAGAZZINI_ACCESSI_INVENTARIO" Member="MAGAZZINI" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="MAGAZZINI" IsForeignKey="true" />
      <Association Name="SERRE_INCUBAZIONE_ACCESSI_INVENTARIO" Member="SERRE_INCUBAZIONE" ThisKey="IDStruttura,IDSerraIncubazione" OtherKey="IDStruttura,IDSerraIncubazione" Type="SERRE_INCUBAZIONE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ANNOTAZIONI" Member="ANNOTAZIONI">
    <Type Name="ANNOTAZIONI">
      <Column Name="IDEsperimento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NumeroAnnotazione" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataOra" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Testo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IDRicercatore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ESPERIMENTI_ANNOTAZIONI" Member="ESPERIMENTI" ThisKey="IDEsperimento" OtherKey="IDEsperimento" Type="ESPERIMENTI" IsForeignKey="true" />
      <Association Name="RICERCATORI_ANNOTAZIONI" Member="RICERCATORI" ThisKey="IDRicercatore" OtherKey="IDRicercatore" Type="RICERCATORI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CLIMI" Member="CLIMI">
    <Type Name="CLIMI">
      <Column Name="IDClima" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Luce" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OreLuce" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Umidità" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Temperatura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CLIMI_SERRE" Member="SERRE" ThisKey="IDClima" OtherKey="IDClima" Type="SERRE" />
    </Type>
  </Table>
  <Table Name="dbo.CLUSTER" Member="CLUSTER">
    <Type Name="CLUSTER">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSerra" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCluster" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dimensione" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ComposizioneNPKTerreno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CLUSTER_CLUSTER_PIANTE" Member="CLUSTER_PIANTE" ThisKey="IDStruttura,IDSerra,IDCluster" OtherKey="IDStruttura,IDSerra,IDCluster" Type="CLUSTER_PIANTE" />
      <Association Name="SERRE_CLUSTER" Member="SERRE" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="SERRE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CLUSTER_EMBRIONI" Member="CLUSTER_EMBRIONI">
    <Type Name="CLUSTER_EMBRIONI">
      <Column Name="IDPianta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDClusterEmbrioni" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataSemina" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataGerminazione" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataUscita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmbrioniFalliti" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDSerraIncubazione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PIANTE_CLUSTER_EMBRIONI" Member="PIANTE" ThisKey="IDPianta" OtherKey="IDPianta" Type="PIANTE" IsForeignKey="true" />
      <Association Name="SERRE_INCUBAZIONE_CLUSTER_EMBRIONI" Member="SERRE_INCUBAZIONE" ThisKey="IDStruttura,IDSerraIncubazione" OtherKey="IDStruttura,IDSerraIncubazione" Type="SERRE_INCUBAZIONE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CLUSTER_PIANTE" Member="CLUSTER_PIANTE">
    <Type Name="CLUSTER_PIANTE">
      <Column Name="IDClusterPiante" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataInizio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataFine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataTrapianto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataEspianto" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumeroPianteIniziali" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumeroPianteMorte" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrattamentoBiologico" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataSmaltimento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDSerra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDCluster" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDEsperimento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDPianta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CLUSTER_PIANTE_IRRIGAZIONI" Member="IRRIGAZIONI" ThisKey="IDClusterPiante" OtherKey="IDClusterPiante" Type="IRRIGAZIONI" />
      <Association Name="CLUSTER_PIANTE_LAVORI_EFFETTUATI" Member="LAVORI_EFFETTUATI" ThisKey="IDClusterPiante" OtherKey="IDClusterPiante" Type="LAVORI_EFFETTUATI" />
      <Association Name="CLUSTER_CLUSTER_PIANTE" Member="CLUSTER" ThisKey="IDStruttura,IDSerra,IDCluster" OtherKey="IDStruttura,IDSerra,IDCluster" Type="CLUSTER" IsForeignKey="true" />
      <Association Name="ESPERIMENTI_CLUSTER_PIANTE" Member="ESPERIMENTI" ThisKey="IDEsperimento" OtherKey="IDEsperimento" Type="ESPERIMENTI" IsForeignKey="true" />
      <Association Name="PIANTE_CLUSTER_PIANTE" Member="PIANTE" ThisKey="IDPianta" OtherKey="IDPianta" Type="PIANTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.COLLABORAZIONI" Member="COLLABORAZIONI">
    <Type Name="COLLABORAZIONI">
      <Column Name="IDEsperimento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDRicercatore" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ESPERIMENTI_COLLABORAZIONI" Member="ESPERIMENTI" ThisKey="IDEsperimento" OtherKey="IDEsperimento" Type="ESPERIMENTI" IsForeignKey="true" />
      <Association Name="RICERCATORI_COLLABORAZIONI" Member="RICERCATORI" ThisKey="IDRicercatore" OtherKey="IDRicercatore" Type="RICERCATORI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTRATTI" Member="CONTRATTI">
    <Type Name="CONTRATTI">
      <Column Name="IDContratto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TipoContratto" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataInizio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataFine" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDDipendente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DIPENDENTI_CONTRATTI" Member="DIPENDENTI" ThisKey="IDDipendente" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
      <Association Name="STRUTTURE_CONTRATTI" Member="STRUTTURE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="STRUTTURE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIPENDENTI" Member="DIPENDENTI">
    <Type Name="DIPENDENTI">
      <Column Name="IDDipendente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CF" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Via" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ruolo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Stipendio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CV" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AbilitazioneProdottiChimici" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="DIPENDENTI_ACCESSI_INVENTARIO" Member="ACCESSI_INVENTARIO" ThisKey="IDDipendente" OtherKey="IDDipendente" Type="ACCESSI_INVENTARIO" />
      <Association Name="DIPENDENTI_CONTRATTI" Member="CONTRATTI" ThisKey="IDDipendente" OtherKey="IDDipendente" Type="CONTRATTI" />
      <Association Name="DIPENDENTI_ESPERIMENTI" Member="ESPERIMENTI" ThisKey="IDDipendente" OtherKey="IDAutorizzante" Type="ESPERIMENTI" />
      <Association Name="DIPENDENTI_LAVORI_EFFETTUATI" Member="LAVORI_EFFETTUATI" ThisKey="IDDipendente" OtherKey="IDManovale" Type="LAVORI_EFFETTUATI" />
      <Association Name="DIPENDENTI_MANUTENZIONI" Member="MANUTENZIONI" ThisKey="IDDipendente" OtherKey="IDManutentore" Type="MANUTENZIONI" />
      <Association Name="DIPENDENTI_PERMESSI" Member="PERMESSI" ThisKey="IDDipendente" OtherKey="IDSupervisoreConcedente" Type="PERMESSI" />
      <Association Name="DIPENDENTI_PERMESSI_MANOVALI" Member="PERMESSI_MANOVALI" ThisKey="IDDipendente" OtherKey="IDManovale" Type="PERMESSI_MANOVALI" />
      <Association Name="DIPENDENTI_STRUTTURE" Member="STRUTTURE" ThisKey="IDDipendente" OtherKey="IDDirettore" Type="STRUTTURE" />
      <Association Name="DIPENDENTI_SUPERVISIONI" Member="SUPERVISIONI" ThisKey="IDDipendente" OtherKey="IDSupervisore" Type="SUPERVISIONI" />
      <Association Name="DIPENDENTI_VIAGGI_ISTRUZIONE" Member="VIAGGI_ISTRUZIONE" ThisKey="IDDipendente" OtherKey="IDGuida" Type="VIAGGI_ISTRUZIONE" />
    </Type>
  </Table>
  <Table Name="dbo.ESPERIMENTI" Member="ESPERIMENTI">
    <Type Name="ESPERIMENTI">
      <Column Name="IDEsperimento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataInizio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataFine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataApprovazione" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IDAutorizzante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDRicercatoreCapo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ESPERIMENTI_ANNOTAZIONI" Member="ANNOTAZIONI" ThisKey="IDEsperimento" OtherKey="IDEsperimento" Type="ANNOTAZIONI" />
      <Association Name="ESPERIMENTI_CLUSTER_PIANTE" Member="CLUSTER_PIANTE" ThisKey="IDEsperimento" OtherKey="IDEsperimento" Type="CLUSTER_PIANTE" />
      <Association Name="ESPERIMENTI_COLLABORAZIONI" Member="COLLABORAZIONI" ThisKey="IDEsperimento" OtherKey="IDEsperimento" Type="COLLABORAZIONI" />
      <Association Name="DIPENDENTI_ESPERIMENTI" Member="DIPENDENTI" ThisKey="IDAutorizzante" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
      <Association Name="RICERCATORI_ESPERIMENTI" Member="RICERCATORI" ThisKey="IDRicercatoreCapo" OtherKey="IDRicercatore" Type="RICERCATORI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GARAGE" Member="GARAGE">
    <Type Name="GARAGE">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDGarage" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcheggiTotali" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcheggiLiberi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GARAGE_ACCESSI_INVENTARIO" Member="ACCESSI_INVENTARIO" ThisKey="IDStruttura,IDGarage" OtherKey="IDStruttura,IDGarage" Type="ACCESSI_INVENTARIO" />
      <Association Name="GARAGE_MACCHINARI" Member="MACCHINARI" ThisKey="IDStruttura,IDGarage" OtherKey="IDStruttura,IDGarage" Type="MACCHINARI" />
      <Association Name="STRUTTURE_GARAGE" Member="STRUTTURE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="STRUTTURE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IRRIGAZIONI" Member="IRRIGAZIONI">
    <Type Name="IRRIGAZIONI">
      <Column Name="IDClusterPiante" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataInizio" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OraInizio" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OraFine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataFine" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PressioneAcqua" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CLUSTER_PIANTE_IRRIGAZIONI" Member="CLUSTER_PIANTE" ThisKey="IDClusterPiante" OtherKey="IDClusterPiante" Type="CLUSTER_PIANTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LAVORI" Member="LAVORI">
    <Type Name="LAVORI">
      <Column Name="IDLavoro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDProdotto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LAVORI_LAVORI_EFFETTUATI" Member="LAVORI_EFFETTUATI" ThisKey="IDLavoro" OtherKey="IDLavoro" Type="LAVORI_EFFETTUATI" />
      <Association Name="PRODOTTI_LAVORI" Member="PRODOTTI" ThisKey="IDStruttura,IDMagazzino,IDProdotto" OtherKey="IDStruttura,IDMagazzino,IDProdotto" Type="PRODOTTI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LAVORI_EFFETTUATI" Member="LAVORI_EFFETTUATI">
    <Type Name="LAVORI_EFFETTUATI">
      <Column Name="IDLavoro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDLavoroEffettuato" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataOraInizio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataOraFine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDClusterPiante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDManovale" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LAVORI_EFFETTUATI_MACCHINARI_UTILIZZATI" Member="MACCHINARI_UTILIZZATI" ThisKey="IDLavoro,IDLavoroEffettuato" OtherKey="IDLavoro,IDLavoroEffettuato" Type="MACCHINARI_UTILIZZATI" />
      <Association Name="LAVORI_EFFETTUATI_STRUMENTI_COMPLESSI_UTILIZZATI" Member="STRUMENTI_COMPLESSI_UTILIZZATI" ThisKey="IDLavoro,IDLavoroEffettuato" OtherKey="IDLavoro,IDLavoroEffettuato" Type="STRUMENTI_COMPLESSI_UTILIZZATI" />
      <Association Name="CLUSTER_PIANTE_LAVORI_EFFETTUATI" Member="CLUSTER_PIANTE" ThisKey="IDClusterPiante" OtherKey="IDClusterPiante" Type="CLUSTER_PIANTE" IsForeignKey="true" />
      <Association Name="LAVORI_LAVORI_EFFETTUATI" Member="LAVORI" ThisKey="IDLavoro" OtherKey="IDLavoro" Type="LAVORI" IsForeignKey="true" />
      <Association Name="DIPENDENTI_LAVORI_EFFETTUATI" Member="DIPENDENTI" ThisKey="IDManovale" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MACCHINARI" Member="MACCHINARI">
    <Type Name="MACCHINARI">
      <Column Name="NumeroTelaio" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Modello" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Targa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataRevisione" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LivelloCarburante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDGarage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MACCHINARI_MACCHINARI_UTILIZZATI" Member="MACCHINARI_UTILIZZATI" ThisKey="NumeroTelaio" OtherKey="NumeroTelaio" Type="MACCHINARI_UTILIZZATI" />
      <Association Name="MACCHINARI_PERMESSI_MACCHINARI" Member="PERMESSI_MACCHINARI" ThisKey="NumeroTelaio" OtherKey="NumeroTelaio" Type="PERMESSI_MACCHINARI" />
      <Association Name="GARAGE_MACCHINARI" Member="GARAGE" ThisKey="IDStruttura,IDGarage" OtherKey="IDStruttura,IDGarage" Type="GARAGE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MACCHINARI_UTILIZZATI" Member="MACCHINARI_UTILIZZATI">
    <Type Name="MACCHINARI_UTILIZZATI">
      <Column Name="IDLavoro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDLavoroEffettuato" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NumeroTelaio" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="LAVORI_EFFETTUATI_MACCHINARI_UTILIZZATI" Member="LAVORI_EFFETTUATI" ThisKey="IDLavoro,IDLavoroEffettuato" OtherKey="IDLavoro,IDLavoroEffettuato" Type="LAVORI_EFFETTUATI" IsForeignKey="true" />
      <Association Name="MACCHINARI_MACCHINARI_UTILIZZATI" Member="MACCHINARI" ThisKey="NumeroTelaio" OtherKey="NumeroTelaio" Type="MACCHINARI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MAGAZZINI" Member="MAGAZZINI">
    <Type Name="MAGAZZINI">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StoccaggioProdottiSensibili" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="MAGAZZINI_ACCESSI_INVENTARIO" Member="ACCESSI_INVENTARIO" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="ACCESSI_INVENTARIO" />
      <Association Name="MAGAZZINI_PRODOTTI" Member="PRODOTTI" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="PRODOTTI" />
      <Association Name="MAGAZZINI_STRUMENTI_COMPLESSI" Member="STRUMENTI_COMPLESSI" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="STRUMENTI_COMPLESSI" />
      <Association Name="MAGAZZINI_UTENSILI" Member="UTENSILI" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="UTENSILI" />
      <Association Name="STRUTTURE_MAGAZZINI" Member="STRUTTURE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="STRUTTURE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MANUTENZIONI" Member="MANUTENZIONI">
    <Type Name="MANUTENZIONI">
      <Column Name="IDManutentore" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataOra" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDSerra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DIPENDENTI_MANUTENZIONI" Member="DIPENDENTI" ThisKey="IDManutentore" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
      <Association Name="SERRE_MANUTENZIONI" Member="SERRE" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="SERRE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERMESSI" Member="PERMESSI">
    <Type Name="PERMESSI">
      <Column Name="IDPermesso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataCreazione" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Validità" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDSupervisoreConcedente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDSerra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDRicercatore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PERMESSI_PERMESSI_MACCHINARI" Member="PERMESSI_MACCHINARI" ThisKey="IDPermesso" OtherKey="IDPermesso" Type="PERMESSI_MACCHINARI" Cardinality="One" />
      <Association Name="PERMESSI_PERMESSI_MANOVALI" Member="PERMESSI_MANOVALI" ThisKey="IDPermesso" OtherKey="IDPermesso" Type="PERMESSI_MANOVALI" Cardinality="One" />
      <Association Name="PERMESSI_PERMESSI_STRUMENTI_COMPLESSI" Member="PERMESSI_STRUMENTI_COMPLESSI" ThisKey="IDPermesso" OtherKey="IDPermesso" Type="PERMESSI_STRUMENTI_COMPLESSI" Cardinality="One" />
      <Association Name="DIPENDENTI_PERMESSI" Member="DIPENDENTI" ThisKey="IDSupervisoreConcedente" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
      <Association Name="RICERCATORI_PERMESSI" Member="RICERCATORI" ThisKey="IDRicercatore" OtherKey="IDRicercatore" Type="RICERCATORI" IsForeignKey="true" />
      <Association Name="SERRE_PERMESSI" Member="SERRE" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="SERRE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERMESSI_MACCHINARI" Member="PERMESSI_MACCHINARI">
    <Type Name="PERMESSI_MACCHINARI">
      <Column Name="IDPermesso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NumeroTelaio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MACCHINARI_PERMESSI_MACCHINARI" Member="MACCHINARI" ThisKey="NumeroTelaio" OtherKey="NumeroTelaio" Type="MACCHINARI" IsForeignKey="true" />
      <Association Name="PERMESSI_PERMESSI_MACCHINARI" Member="PERMESSI" ThisKey="IDPermesso" OtherKey="IDPermesso" Type="PERMESSI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERMESSI_MANOVALI" Member="PERMESSI_MANOVALI">
    <Type Name="PERMESSI_MANOVALI">
      <Column Name="IDPermesso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDManovale" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DIPENDENTI_PERMESSI_MANOVALI" Member="DIPENDENTI" ThisKey="IDManovale" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
      <Association Name="PERMESSI_PERMESSI_MANOVALI" Member="PERMESSI" ThisKey="IDPermesso" OtherKey="IDPermesso" Type="PERMESSI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERMESSI_STRUMENTI_COMPLESSI" Member="PERMESSI_STRUMENTI_COMPLESSI">
    <Type Name="PERMESSI_STRUMENTI_COMPLESSI">
      <Column Name="IDPermesso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDStrumentoComplesso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PERMESSI_PERMESSI_STRUMENTI_COMPLESSI" Member="PERMESSI" ThisKey="IDPermesso" OtherKey="IDPermesso" Type="PERMESSI" IsForeignKey="true" />
      <Association Name="STRUMENTI_COMPLESSI_PERMESSI_STRUMENTI_COMPLESSI" Member="STRUMENTI_COMPLESSI" ThisKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" OtherKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" Type="STRUMENTI_COMPLESSI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PIANTE" Member="PIANTE">
    <Type Name="PIANTE">
      <Column Name="IDPianta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Razza" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Varietà" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UnitàOccupate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PIANTE_CLUSTER_EMBRIONI" Member="CLUSTER_EMBRIONI" ThisKey="IDPianta" OtherKey="IDPianta" Type="CLUSTER_EMBRIONI" />
      <Association Name="PIANTE_CLUSTER_PIANTE" Member="CLUSTER_PIANTE" ThisKey="IDPianta" OtherKey="IDPianta" Type="CLUSTER_PIANTE" />
    </Type>
  </Table>
  <Table Name="dbo.PRODOTTI" Member="PRODOTTI">
    <Type Name="PRODOTTI">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDProdotto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tipologia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrincipioAttivo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diluizione" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="GiorniEffetto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sensibile" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Quantità" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PRODOTTI_LAVORI" Member="LAVORI" ThisKey="IDStruttura,IDMagazzino,IDProdotto" OtherKey="IDStruttura,IDMagazzino,IDProdotto" Type="LAVORI" />
      <Association Name="MAGAZZINI_PRODOTTI" Member="MAGAZZINI" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="MAGAZZINI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RICERCATORI" Member="RICERCATORI">
    <Type Name="RICERCATORI">
      <Column Name="IDRicercatore" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CF" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Via" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Competenza" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dipartimento" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NomeUniversità" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RICERCATORI_ANNOTAZIONI" Member="ANNOTAZIONI" ThisKey="IDRicercatore" OtherKey="IDRicercatore" Type="ANNOTAZIONI" />
      <Association Name="RICERCATORI_COLLABORAZIONI" Member="COLLABORAZIONI" ThisKey="IDRicercatore" OtherKey="IDRicercatore" Type="COLLABORAZIONI" />
      <Association Name="RICERCATORI_ESPERIMENTI" Member="ESPERIMENTI" ThisKey="IDRicercatore" OtherKey="IDRicercatoreCapo" Type="ESPERIMENTI" />
      <Association Name="RICERCATORI_PERMESSI" Member="PERMESSI" ThisKey="IDRicercatore" OtherKey="IDRicercatore" Type="PERMESSI" />
      <Association Name="UNIVERSITÀ_RICERCATORI" Member="UNIVERSITÀ" ThisKey="NomeUniversità" OtherKey="Nome" Type="UNIVERSITÀ" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SERRE" Member="SERRE">
    <Type Name="SERRE">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSerra" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Area" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumeroUnitàMassime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumeroUnitàOccupate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDClima" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SERRE_CLUSTER" Member="CLUSTER" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="CLUSTER" />
      <Association Name="SERRE_MANUTENZIONI" Member="MANUTENZIONI" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="MANUTENZIONI" />
      <Association Name="SERRE_PERMESSI" Member="PERMESSI" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="PERMESSI" />
      <Association Name="SERRE_SUPERVISIONI" Member="SUPERVISIONI" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="SUPERVISIONI" />
      <Association Name="SERRE_VISITE" Member="VISITE" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="VISITE" />
      <Association Name="CLIMI_SERRE" Member="CLIMI" ThisKey="IDClima" OtherKey="IDClima" Type="CLIMI" IsForeignKey="true" />
      <Association Name="STRUTTURE_SERRE" Member="STRUTTURE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="STRUTTURE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SERRE_INCUBAZIONE" Member="SERRE_INCUBAZIONE">
    <Type Name="SERRE_INCUBAZIONE">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSerraIncubazione" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClusterOspitabili" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClusterPresenti" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SERRE_INCUBAZIONE_ACCESSI_INVENTARIO" Member="ACCESSI_INVENTARIO" ThisKey="IDStruttura,IDSerraIncubazione" OtherKey="IDStruttura,IDSerraIncubazione" Type="ACCESSI_INVENTARIO" />
      <Association Name="SERRE_INCUBAZIONE_CLUSTER_EMBRIONI" Member="CLUSTER_EMBRIONI" ThisKey="IDStruttura,IDSerraIncubazione" OtherKey="IDStruttura,IDSerraIncubazione" Type="CLUSTER_EMBRIONI" />
      <Association Name="STRUTTURE_SERRE_INCUBAZIONE" Member="STRUTTURE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="STRUTTURE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STRUMENTI_COMPLESSI" Member="STRUMENTI_COMPLESSI">
    <Type Name="STRUMENTI_COMPLESSI">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDStrumentoComplesso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Alimentazione" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantità" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="STRUMENTI_COMPLESSI_PERMESSI_STRUMENTI_COMPLESSI" Member="PERMESSI_STRUMENTI_COMPLESSI" ThisKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" OtherKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" Type="PERMESSI_STRUMENTI_COMPLESSI" />
      <Association Name="STRUMENTI_COMPLESSI_STRUMENTI_COMPLESSI_UTILIZZATI" Member="STRUMENTI_COMPLESSI_UTILIZZATI" ThisKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" OtherKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" Type="STRUMENTI_COMPLESSI_UTILIZZATI" />
      <Association Name="MAGAZZINI_STRUMENTI_COMPLESSI" Member="MAGAZZINI" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="MAGAZZINI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STRUMENTI_COMPLESSI_UTILIZZATI" Member="STRUMENTI_COMPLESSI_UTILIZZATI">
    <Type Name="STRUMENTI_COMPLESSI_UTILIZZATI">
      <Column Name="IDLavoro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDLavoroEffettuato" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDStrumentoComplesso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="STRUMENTI_COMPLESSI_STRUMENTI_COMPLESSI_UTILIZZATI" Member="STRUMENTI_COMPLESSI" ThisKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" OtherKey="IDStruttura,IDMagazzino,IDStrumentoComplesso" Type="STRUMENTI_COMPLESSI" IsForeignKey="true" />
      <Association Name="LAVORI_EFFETTUATI_STRUMENTI_COMPLESSI_UTILIZZATI" Member="LAVORI_EFFETTUATI" ThisKey="IDLavoro,IDLavoroEffettuato" OtherKey="IDLavoro,IDLavoroEffettuato" Type="LAVORI_EFFETTUATI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STRUTTURE" Member="STRUTTURE">
    <Type Name="STRUTTURE">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Via" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataInizioGestione" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDDirettore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="STRUTTURE_CONTRATTI" Member="CONTRATTI" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="CONTRATTI" />
      <Association Name="STRUTTURE_GARAGE" Member="GARAGE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="GARAGE" />
      <Association Name="STRUTTURE_MAGAZZINI" Member="MAGAZZINI" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="MAGAZZINI" />
      <Association Name="STRUTTURE_SERRE" Member="SERRE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="SERRE" />
      <Association Name="STRUTTURE_SERRE_INCUBAZIONE" Member="SERRE_INCUBAZIONE" ThisKey="IDStruttura" OtherKey="IDStruttura" Type="SERRE_INCUBAZIONE" />
      <Association Name="DIPENDENTI_STRUTTURE" Member="DIPENDENTI" ThisKey="IDDirettore" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SUPERVISIONI" Member="SUPERVISIONI">
    <Type Name="SUPERVISIONI">
      <Column Name="IDSupervisore" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataInizio" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataFine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDSerra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SERRE_SUPERVISIONI" Member="SERRE" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="SERRE" IsForeignKey="true" />
      <Association Name="DIPENDENTI_SUPERVISIONI" Member="DIPENDENTI" ThisKey="IDSupervisore" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UNIVERSITÀ" Member="UNIVERSITÀ">
    <Type Name="UNIVERSITÀ">
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Via" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="UNIVERSITÀ_RICERCATORI" Member="RICERCATORI" ThisKey="Nome" OtherKey="NomeUniversità" Type="RICERCATORI" />
    </Type>
  </Table>
  <Table Name="dbo.UTENSILI" Member="UTENSILI">
    <Type Name="UTENSILI">
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMagazzino" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDUtensile" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantità" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MAGAZZINI_UTENSILI" Member="MAGAZZINI" ThisKey="IDStruttura,IDMagazzino" OtherKey="IDStruttura,IDMagazzino" Type="MAGAZZINI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIAGGI_ISTRUZIONE" Member="VIAGGI_ISTRUZIONE">
    <Type Name="VIAGGI_ISTRUZIONE">
      <Column Name="IDViaggio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PrimaData" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Scuola" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroPartecipanti" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrdineScolastico" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDGuida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="VIAGGI_ISTRUZIONE_VISITE" Member="VISITE" ThisKey="IDViaggio" OtherKey="IDViaggio" Type="VISITE" />
      <Association Name="DIPENDENTI_VIAGGI_ISTRUZIONE" Member="DIPENDENTI" ThisKey="IDGuida" OtherKey="IDDipendente" Type="DIPENDENTI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VISITE" Member="VISITE">
    <Type Name="VISITE">
      <Column Name="IDViaggio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataOra" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDStruttura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDSerra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="VIAGGI_ISTRUZIONE_VISITE" Member="VIAGGI_ISTRUZIONE" ThisKey="IDViaggio" OtherKey="IDViaggio" Type="VIAGGI_ISTRUZIONE" IsForeignKey="true" />
      <Association Name="SERRE_VISITE" Member="SERRE" ThisKey="IDStruttura,IDSerra" OtherKey="IDStruttura,IDSerra" Type="SERRE" IsForeignKey="true" />
    </Type>
  </Table>
</Database>